=== globalwordnet/schemas/WN-LMF-1.5.dtd
<?xml version='1.0' encoding="UTF-8"?>
<!ELEMENT LexicalResource (Lexicon|LexiconExtension)+>
<!ATTLIST LexicalResource
    xmlns:dc CDATA #FIXED "https://globalwordnet.github.io/schemas/dc/">
<!ELEMENT Lexicon (Requires*, LexicalEntry+, Synset*, SyntacticBehaviour*)>
<!ATTLIST Lexicon
    id ID #REQUIRED
    label CDATA #REQUIRED
    language CDATA #REQUIRED
    email CDATA #REQUIRED
    license CDATA #REQUIRED
    version CDATA #REQUIRED
    url CDATA #IMPLIED
    citation CDATA #IMPLIED
    logo CDATA #IMPLIED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA "1.0">
<!ELEMENT LexicalEntry (Lemma, Form*, Sense*, SyntacticBehaviour*)>
<!ATTLIST LexicalEntry
    id ID #REQUIRED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    index CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT Lemma (Pronunciation*, Tag*)>
<!ATTLIST Lemma
    writtenForm CDATA #REQUIRED
    script CDATA #IMPLIED
    partOfSpeech (n|v|a|r|s|t|c|p|x|u) #REQUIRED>
<!ELEMENT Form (Pronunciation*, Tag*)>
<!ATTLIST Form
    id ID #IMPLIED
    writtenForm CDATA #REQUIRED
    script CDATA #IMPLIED>
<!ELEMENT Pronunciation (#PCDATA)>
<!ATTLIST Pronunciation
    xml:space (default|preserve) "default"
    variety CDATA #IMPLIED
    notation CDATA #IMPLIED
    phonemic (true|false) "true"
    audio CDATA #IMPLIED>
<!ELEMENT Tag (#PCDATA)>
<!ATTLIST Tag
    xml:space (default|preserve) "default"
    category CDATA #REQUIRED>
<!ELEMENT Sense (SenseRelation*, Example*, Count*)>
<!ATTLIST Sense
    id ID #REQUIRED
    synset IDREF #REQUIRED
    n CDATA #IMPLIED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED
    lexicalized (true|false) "true"
    adjposition (a|ip|p) #IMPLIED
    subcat IDREFS #IMPLIED>
<!ELEMENT Synset (Definition*, ILIDefinition?, SynsetRelation*, Example*)>
<!ATTLIST Synset
    id ID #REQUIRED
    ili CDATA #REQUIRED
    partOfSpeech (n|v|a|r|s|t|c|p|x|u) #IMPLIED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED
    lexicalized (true|false) "true"
    members IDREFS #IMPLIED
    lexfile CDATA #IMPLIED>
<!ELEMENT Definition (#PCDATA)>
<!ATTLIST Definition
    xml:space (default|preserve) "default"
    language CDATA #IMPLIED
    sourceSense IDREF #IMPLIED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT ILIDefinition (#PCDATA)>
<!ATTLIST ILIDefinition
    xml:space (default|preserve) "default"
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT Example (#PCDATA)>
<!ATTLIST Example
    xml:space (default|preserve) "default"
    language CDATA #IMPLIED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT SynsetRelation EMPTY>
<!ATTLIST SynsetRelation
    target IDREF #REQUIRED
    relType (agent|also|attribute|be_in_state|causes|classified_by|classifies|co_agent_instrument|co_agent_patient|co_agent_result|co_instrument_agent|co_instrument_patient|co_instrument_result|co_patient_agent|co_patient_instrument|co_result_agent|co_result_instrument|co_role|direction|domain_region|domain_topic|exemplifies|entails|eq_synonym|has_domain_region|has_domain_topic|is_exemplified_by|holo_location|holo_member|holo_part|holo_portion|holo_substance|holonym|hypernym|hyponym|in_manner|instance_hypernym|instance_hyponym|instrument|involved|involved_agent|involved_direction|involved_instrument|involved_location|involved_patient|involved_result|involved_source_direction|involved_target_direction|is_caused_by|is_entailed_by|location|manner_of|mero_location|mero_member|mero_part|mero_portion|mero_substance|meronym|similar|other|patient|restricted_by|restricts|result|role|source_direction|state_of|target_direction|subevent|is_subevent_of|antonym|feminine|has_feminine|masculine|has_masculine|young|has_young|diminutive|has_diminutive|augmentative|has_augmentative|anto_gradable|anto_simple|anto_converse|ir_synonym) #REQUIRED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT SenseRelation EMPTY>
<!ATTLIST SenseRelation
    target IDREF #REQUIRED
    relType (antonym|also|participle|pertainym|derivation|domain_topic|has_domain_topic|domain_region|has_domain_region|exemplifies|is_exemplified_by|similar|collocation|other|simple_aspect_ip|secondary_aspect_ip|simple_aspect_pi|secondary_aspect_pi|feminine|has_feminine|masculine|has_masculine|young|has_young|diminutive|has_diminutive|augmentative|has_augmentative|anto_gradable|anto_simple|anto_converse|metaphor|has_metaphor|metonym|has_metonym|agent|material|event|instrument|location|by_means_of|undergoer|property|result|state|uses|destination|body_part|vehicle) #REQUIRED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT SyntacticBehaviour EMPTY>
<!ATTLIST SyntacticBehaviour
  id ID #IMPLIED
  subcategorizationFrame CDATA #REQUIRED
  senses IDREFS #IMPLIED>
<!ELEMENT Count (#PCDATA)>
<!ATTLIST Count
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA #IMPLIED>
<!ELEMENT LexiconExtension (Extends, Requires*, (LexicalEntry|ExternalLexicalEntry)*, (Synset|ExternalSynset)*, SyntacticBehaviour*)>
<!ATTLIST LexiconExtension
    id ID #REQUIRED
    label CDATA #REQUIRED
    language CDATA #REQUIRED
    email CDATA #REQUIRED
    license CDATA #REQUIRED
    version CDATA #REQUIRED
    url CDATA #IMPLIED
    citation CDATA #IMPLIED
    dc:contributor CDATA #IMPLIED
    dc:coverage CDATA #IMPLIED
    dc:creator CDATA #IMPLIED
    dc:date CDATA #IMPLIED
    dc:description CDATA #IMPLIED
    dc:format CDATA #IMPLIED
    dc:identifier CDATA #IMPLIED
    dc:publisher CDATA #IMPLIED
    dc:relation CDATA #IMPLIED
    dc:rights CDATA #IMPLIED
    dc:source CDATA #IMPLIED
    dc:subject CDATA #IMPLIED
    dc:title CDATA #IMPLIED
    dc:type CDATA #IMPLIED
    status CDATA #IMPLIED
    note CDATA #IMPLIED
    confidenceScore CDATA "1.0">
<!ELEMENT Requires EMPTY>
<!ATTLIST Requires
    ref CDATA #REQUIRED
    version CDATA #REQUIRED
    url CDATA #IMPLIED>
<!ELEMENT Extends EMPTY>
<!ATTLIST Extends
    ref CDATA #REQUIRED
    version CDATA #REQUIRED
    url CDATA #IMPLIED>
<!ELEMENT ExternalLexicalEntry (ExternalLemma?, (Form|ExternalForm)*, (Sense|ExternalSense)*, SyntacticBehaviour*)>
<!ATTLIST ExternalLexicalEntry
    id ID #REQUIRED>
<!ELEMENT ExternalLemma (Pronunciation*, Tag*)>
<!ELEMENT ExternalForm (Pronunciation*, Tag*)>
<!ATTLIST ExternalForm
    id ID #REQUIRED>
<!ELEMENT ExternalSense (SenseRelation*, Example*, Count*)>
<!ATTLIST ExternalSense
    id ID #REQUIRED>
<!ELEMENT ExternalSynset (Definition*, SynsetRelation*, Example*)>
<!ATTLIST ExternalSynset
    id ID #REQUIRED>

=== globalwordnet/schemas/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LexicalResource SYSTEM "http://globalwordnet.github.io/schemas/WN-LMF-1.5.dtd">
<LexicalResource xmlns:dc="https://globalwordnet.github.io/schemas/dc/">
    <!-- The first three lines must always be as above -->

    <!-- A file may contain multiple WordNets in different languages:
         The following information is required:
            id: A short name for the resource
            label: The full name for the resources
            language: Please follow BCP-47, i.e., use a two-letter code if 
                      available else a three-letter code
            email: Please give a contact email address
            license: The license of your resource (please provide URL)
            version: A string identifying this version (preferably follow 
                     major.minor format)
            url: A URL for your project homepage
            citation: The paper to cite for this resource
         Extra properties may be included from Dublin core and in addition
            status: The status of the resource, e.g., "valid", "checked", "unchecked"
            confidenceScore: A numeric value between 0 and 1 giving the 
                             confidence in the correctness of the element.                             
    -->
    <Lexicon id="example-en"
             label="Example wordnet (English)"
             language="en" 
             email="john@mccr.ae"
             license="https://creativecommons.org/publicdomain/zero/1.0/"
             version="1.0"
             citation="CILI: the Collaborative Interlingual Index. Francis Bond, Piek Vossen, John P. McCrae and Christiane Fellbaum, Proceedings of the Global WordNet Conference 2016, (2016)."
             url="http://globalwordnet.github.io/schemas/"
             dc:publisher="Global Wordnet Association">
        <!-- The list of lexical entries (words) in your wordnet -->
        <LexicalEntry id="w1">
            <!-- The part of speech values are as follows:
                 n: Noun
                 v: Verb
                 a: Adjective
                 r: Adverb
                 s: Adjective Satellite
                 z: Multiword expression (inc. phrase, idiom)
                 c: Conjunction
                 p: Adposition (Preposition, postposition, etc.)
                 x: Other (inc. particle, classifier, bound morpheme, determiner)
                 u: Unknown -->
            <Lemma writtenForm="grandfather" partOfSpeech="n"/>
            <Sense id="example-en-10161911-n-1" synset="example-en-10161911-n">
            </Sense>
        </LexicalEntry>
        <LexicalEntry id="w2">
            <Lemma writtenForm="paternal grandfather" partOfSpeech="n"/>
            <Sense id="example-en-1-n-1" synset="example-en-1-n">
                <!-- The set of relations between senses is limited to the following
                     antonym: An opposite and inherently incompatible word
                     also: See also, a reference of weak meaning
                     participle: An adjective that is a participle form a verb
                     pertainym: A relational adjective. Adjectives that are pertainyms are usually defined by such phrases as "of or pertaining to" and do not have antonyms. A pertainym can point to a noun or another pertainym
                     derivation: A word that is derived from some other word
                     domain_category: Indicates the category of this word
                     domain_member_category: Indicates a word involved in this category described by this word
                     domain_region: Indicates the region of this word
                     domain_member_region: Indicates a word involved in the region described by this word
                     exemplifies: Indicates the usage of this word
                     is_exemplified_by: Indicates a word involved in the usage described by this word
                -->
                <SenseRelation relType="derivation" target="example-en-10161911-n-1"/>
            </Sense>
        </LexicalEntry>
        <LexicalEntry id="w3">
            <Lemma writtenForm="pay" partOfSpeech="v"/>
            <!-- Syntactic Behaviour is given as in Princeton WordNet -->

            <SyntacticBehaviour subcategorizationFrame="Somebody ----s" id="intransitive"/>
            <SyntacticBehaviour subcategorizationFrame="Somebody ----s somebody" id="transitive"/>
        </LexicalEntry>
        <!-- If a synset is already mapped to the ILI please give the ID here -->
        <Synset id="example-en-10161911-n" ili="i90287" partOfSpeech="n"
                members="example-en-10161911-n-1 example-en-1-n-1">
            <Definition>the father of your father or mother</Definition>
            <!-- The set of relations between synsets is limited to the following:
                    hypernym: A concept with a broader meaning
                    hyponym: A concept with a narrower meaning
                    instance_hypernym: The class of objects to which this instance belongs
                    instance_hyponym: An individual instance of this class
                    part_holonym: A larger whole that this concept is part of
                    part_meronym: A part of this concept
                    member_holonym: A group that this concept is a member of
                    member_meronym: A member of this concept
                    substance_holonym: Something where a constituent material is this concept
                    substance_meronym: A constituent material of this concept
                    entail: A verb X entails Y if X cannot be done unless Y is, or has been, done.
                    cause: A verb that causes another
                    similar: Similar, though not necessarily interchangeable
                    also: See also, a reference of weak meaning
                    attribute: A noun for which adjectives express values. The noun weight is an attribute, for which the adjectives light and heavy express values.
                    domain_category: Indicates the category of this word
                    domain_member_category: Indicates a word involved in this category described by this word
                    domain_region: Indicates the region of this word
                    domain_member_region: Indicates a word involved in the region described by this word
                    exemplifies: Indicates the usage of this word
                    is_exemplified_by: Indicates a word involved in the usage described by this word
                -->
            <SynsetRelation relType="hypernym" target="example-en-10162692-n"/>
        </Synset>
        <!-- If you wish to define a new concept call the concept "in" (ILI New) -->
        <Synset id="example-en-1-n" ili="in" partOfSpeech="n">
            <Definition>A father&apos;s father; a paternal grandfather</Definition>
            <!-- You can include metadata (such as source) at many points -->
            <!-- The ILI Definition must be at least 20 characters or five words -->
            <ILIDefinition dc:source="https://en.wiktionary.org/wiki/farfar">A father&apos;s father; a paternal grandfather</ILIDefinition>
        </Synset>
        <!-- You must include all targets of relations -->
        <Synset id="example-en-10162692-n" ili="i90292" partOfSpeech="n">
        </Synset>
    </Lexicon>
    <Lexicon id="example_sv"
             label="Example wordnet (Swedish)"
             language="sv" 
             email="john@mccr.ae"
             license="https://creativecommons.org/publicdomain/zero/1.0/"
             version="1.0"
             citation="CILI: the Collaborative Interlingual Index. Francis Bond, Piek Vossen, John P. McCrae and Christiane Fellbaum, Proceedings of the Global WordNet Conference 2016, (2016)."
             url="http://globalwordnet.github.io/schemas/"
             dc:publisher="Global Wordnet Association">
        <!-- The list of lexical entries (words) in your wordnet -->
        <LexicalEntry id="w4">
            <Lemma writtenForm="farfar" partOfSpeech="n"/>
            <Form  writtenForm="farfäder">
                <Tag category="penn">NNS</Tag>
            </Form>
            <!-- Synsets need not be language-specific but senses must be -->
            <Sense id="example-sv-2-n-1" synset="example-en-1-n">
                <Example dc:source="Europarl Corpus">Jag vill berätta för er att min farfar var svensk beredskapssoldat vid norska gränsen under andra världskriget, ett krig som Sverige stod utanför</Example>
            </Sense>
        </LexicalEntry>
    </Lexicon>
    <!-- LexiconExtensions build on top of some external wordnet. The
         external lexicon must not be in the same document as the
         extension, for technical reasons, and therefore any referenced
         LexicalEntry, Sense, or Synset ids must be present as special
         "external" entities. This example adds a new sense of "process"
         (for a computer process) and a synset. In order to link it to
         the external lexicon, the LexicalEntry for "process" and the
         hypernym of the introduced synset are external entities. -->
    <LexiconExtension id="ewn-cs-example"
                      label="English WordNet Computer Science Terms (example)"
                      language="en"
                      email="goodmami@uw.edu"
                      license="https://creativecommons.org/publicdomain/zero/1.0/"
                      version="1.0">
        <Extends ref="ewn" version="2020" />
        <!-- The ExternalLexicalEntry id should exist in ewn-2020 -->
        <ExternalLexicalEntry id="ewn-process-n">
            <!-- Add a new sense to the external entry -->
            <Sense id="ewn-process-n-20000123" synset="ewn-20000123-n" />
        </ExternalLexicalEntry>
        <!-- External for "computer program" synset; it is only
             introduced so its id can be referenced in the
